# generated by gemini
import os
import ast
import sys

def get_args_string(args_node):
    """Helper to convert function arguments node to a string."""
    args = [arg.arg for arg in args_node.args]
    return ", ".join(args)

def get_file_docs(filepath):
    """
    Parses a python file and returns a dictionary containing:
    - filename
    - module_docstring
    - classes (list of dicts)
    - functions (list of dicts: top-level functions)
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        try:
            file_content = f.read()
            tree = ast.parse(file_content)
        except SyntaxError:
            return None

    # Module Docstring
    module_doc = ast.get_docstring(tree) or "No module docstring provided."
    
    classes_data = []
    functions_data = []

    for node in tree.body:
        # 1. Handle Top-Level Functions
        if isinstance(node, ast.FunctionDef):
            func_doc = ast.get_docstring(node) or "No docstring provided."
            functions_data.append({
                "name": node.name,
                "args": get_args_string(node.args),
                "doc": func_doc
            })

        # 2. Handle Classes
        elif isinstance(node, ast.ClassDef):
            class_doc = ast.get_docstring(node) or "No class docstring."
            methods_data = []
            
            # Iterate through the body of the class to find methods
            for sub_node in node.body:
                if isinstance(sub_node, ast.FunctionDef):
                    method_doc = ast.get_docstring(sub_node) or "No docstring."
                    methods_data.append({
                        "name": sub_node.name,
                        "args": get_args_string(sub_node.args),
                        "doc": method_doc
                    })
            
            classes_data.append({
                "name": node.name,
                "doc": class_doc,
                "methods": methods_data
            })

    return {
        "filename": os.path.basename(filepath),
        "module_doc": module_doc,
        "classes": classes_data,
        "functions": functions_data
    }

def generate_markdown(output_file="DOCS.md"):
    current_script = os.path.basename(__file__)
    files_processed = []
    
    for filename in os.listdir('.'):
        if filename.endswith(".py") and filename != current_script:
            print(f"Processing {filename}...")
            doc_data = get_file_docs(filename)
            if doc_data:
                files_processed.append(doc_data)

    if not files_processed:
        print("No Python files found.")
        return

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# API Documentation\n\n")
        f.write("> Auto-generated documentation for all modules, classes, and functions.\n\n")
        f.write("---\n\n")

        for data in files_processed:
            f.write(f"## File: `{data['filename']}`\n\n")
            
            # Module Docstring
            f.write("### Description\n")
            f.write(f"> {data['module_doc']}\n\n")

            # --- CLASSES SECTION ---
            if data['classes']:
                f.write("### Classes\n\n")
                for cls in data['classes']:
                    f.write(f"#### `class {cls['name']}`\n")
                    f.write(f"> {cls['doc']}\n\n")
                    
                    if cls['methods']:
                        f.write("**Methods:**\n\n")
                        for method in cls['methods']:
                            f.write(f"- **`{method['name']}({method['args']})`**\n")
                            f.write(f"  - {method['doc']}\n")
                    f.write("\n")
            
            # --- FUNCTIONS SECTION ---
            if data['functions']:
                f.write("### Top-Level Functions\n\n")
                for func in data['functions']:
                    f.write(f"#### `def {func['name']}({func['args']})`\n")
                    f.write(f"{func['doc']}\n\n")

            f.write("---\n\n")
    
    print(f"Successfully updated {output_file}")

if __name__ == "__main__":
    generate_markdown()